In [1240]:
import pandas as pd

In [1241]:
raw_csv_data = pd.read_csv("Absenteeism-data.csv")

In [1242]:
type(raw_csv_data) #dataframes

pandas.core.frame.DataFrame

In [1243]:
raw_csv_data.head() # always check your data and file

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [1244]:
df = raw_csv_data.copy()  # you can copy your data just in case you can always return

In [1245]:
df.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [1246]:
pd.options.display.max_columns = None #sometimes you might not be able to see all your columns
# use this to overcome this 
#none means NO LIMIT, so you can see everything
pd.options.display.max_rows = None

In [1247]:
df.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [1248]:
#info about each column and datatype
#non null means no missing values
df.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


## Drop 'ID':

In [1249]:
# ID values cannot improve our analysis its just numbers of IDs
# its not related therefore its better to DROP it
# when you have unnecesssary data, its harmful for your analysis and predictions
# axis 1 means drop the ID column
# if you type nothing it will search for rows as axis 0
#drop temporarily drops therefore you must assign to a new variable or you can reassign!
# df.drop(['ID'], axis = 1)

In [1250]:
df = df.drop(['ID'], axis = 1)# here we reassigned now we dont have ID column!

In [1251]:
df.head(5)

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [1252]:
raw_csv_data.head(5)

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

## 'Reason for Absence':

In [1253]:
df['Reason for Absence'].min()

0

In [1254]:
df['Reason for Absence'].max()

28

In [1255]:
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [1256]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [1257]:
len(df['Reason for Absence'].unique()) 

28

In [1258]:
# what kind of values you have here
# how many and unique values
#imagine you have 28 reasons for absence
# you need to express this SOMEHOW
#below you see how with help of get dummies

In [1259]:
# check the values and you see number 20 is missing!
#better visualization when you want to detect missing unique value
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

### .get_dummies()

In [1260]:
reason_columns = pd.get_dummies(df['Reason for Absence'])
#converts categorical columns into dummy variables
# reasons cannot be understood by numbers, thats why we need a strategy
#analyse them one by one
#these reasons are EQUAL number can be bigger but REASONS are equal 

In [1261]:

#dummy variables: an explanatory binary variable that equals to 1 if a ceertain categorical effect is present
# and that equals to 0 if the same effect is absent
reason_columns.head(5)

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

   19  21  22  23  24  25  26  27  28  
0   0   0   0   0   0   0   1   0   0  
1   0   0   0   0   0   0   0   0   0  
2   0   0   0   1   0   0   0   0   0  
3   0   0   0   0   0   0   0   0   0  
4   0   0   0   1   0   0   0   0   0

In [1262]:
# check that is there a 1 for each column!
reason_columns['check'] = reason_columns.sum(axis=1) 
reason_columns.head(5)

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  21  \
0  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
1  1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
3  0  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   

   22  23  24  25  26  27  28  check  
0   0   0   0   0   1   0   0      1  
1   0   0   0   0   0   0   0      1  
2   0   1   0   0   0   0   0      1  
3   0   0   0   0   0   0   0      1  
4   0   1   0   0   0   0   0      1

In [1263]:
#make sure that how many different values in check column
# so indeed there are no incorrect values 
# you can drop this column because we only wanted to check the get dummies

In [1264]:
reason_columns['check'].sum(axis=0)

700

In [1265]:
reason_columns['check'].unique() 

array([1])

In [1266]:
reason_columns = reason_columns.drop(['check'], axis = 1)
reason_columns.head(5)

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  21  \
0  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
1  1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
3  0  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   

   22  23  24  25  26  27  28  
0   0   0   0   0   1   0   0  
1   0   0   0   0   0   0   0  
2   0   1   0   0   0   0   0  
3   0   0   0   0   0   0   0  
4   0   1   0   0   0   0   0

In [1267]:
reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first = True)

## Group the Reasons for Absence:

In [1268]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [1269]:
reason_columns.columns.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28])

In [1270]:
df = df.drop(['Reason for Absence'], axis = 1) #its time to drop this column and we will replace the new one

In [1271]:
df.head(5)

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [1272]:
reason_columns.loc[:, 1:14].max(axis=1) # we will use reasoncolumn
# we dont wanna have duplicate values this will caluse multicolinearity ( you dont want that)

0      0
1      0
2      0
3      1
4      0
5      0
6      0
7      0
8      0
9      0
10     1
11     1
12     1
13     1
14     0
15     1
16     0
17     0
18     1
19     0
20     1
21     1
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     1
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     1
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     1
76     0
77     0
78     0
79     0
80     0
81     0
82     1
83     0
84     0
85     1
86     0
87     1
88     0
89     1
90     0
91     0
92     1
93     0
94     0
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
1

In [1273]:
reason_type_1 = reason_columns.loc[:, 1:14].max(axis=1) # its better to have it less groups as 4 here
reason_type_2 = reason_columns.loc[:, 15:17].max(axis=1) # otherwise you will have around 40 columns, not good
reason_type_3 = reason_columns.loc[:, 18:21].max(axis=1)
reason_type_4 = reason_columns.loc[:, 22:].max(axis=1)
# how to group, you must regroup by relation
# those 4 oness as diseases, pregnancy, poisoning, consultations 
# so you have 4 groups now
# retrieve all rows and retrieve between 1 to 14 columns and make it GROUP 1 as reasonType1

In [1274]:
reason_type_2

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     0
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     0
78     0
79     0
80     0
81     0
82     0
83     0
84     0
85     0
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     0
94     0
95     0
96     0
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
1

## Concatenate Column Values

In [1275]:
df.head(5)

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [1276]:
df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis = 1)
df.head(5) #concatenate everything and add it to our dataframe

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  0  1  2  3  
0                          4  0  0  0  1  
1                          0  0  0  0  0  
2                          2  0  0  0  1  
3                          4  1  0  0  0  
4                          2  0  0  0  1

In [1277]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [1278]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']
#rename your columns by adding Reasons!!!
# do not leave your columns named as 1 2 3 4, make it beautiful

In [1279]:
df.columns = column_names

In [1280]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  
0                          4         0         0         0         1  
1                          0         0         0         0         0  
2                          2         0         0         0         1  
3                          4         1         0         0         0  
4                          2         0         0         0         1

## Reorder Columns

In [1281]:
column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 
                          'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [1282]:
df = df[column_names_reordered] # reorder as it was in the beginning to make it even more beautiful!
# 

In [1283]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

## Create a Checkpoint

In [1284]:
df_reason_mod = df.copy() # to be or not to be its all matters

In [1285]:
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

## 'Date':

In [1286]:
type(df_reason_mod['Date'][0])

str

In [1287]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'])

/tmp/ipykernel_3212/4161912285.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'])


In [1288]:
df_reason_mod['Date'] # now there are  dashes instead of slashes

0     2015-07-07
1     2015-07-14
2     2015-07-15
3     2015-07-16
4     2015-07-23
5     2015-10-07
6     2015-07-17
7     2015-07-24
8     2015-06-07
9     2015-07-13
10    2015-07-20
11    2015-07-14
12    2015-07-15
13    2015-07-15
14    2015-07-15
15    2015-07-17
16    2015-07-17
17    2015-07-27
18    2015-07-30
19    2015-05-08
20    2015-12-08
21    2015-03-08
22    2015-10-08
23    2015-08-14
24    2015-08-17
25    2015-08-24
26    2015-04-08
27    2015-12-08
28    2015-08-19
29    2015-08-28
30    2015-08-17
31    2015-08-27
32    2015-08-27
33    2015-08-17
34    2015-08-17
35    2015-08-17
36    2015-04-08
37    2015-08-20
38    2015-08-21
39    2015-08-28
40    2015-01-09
41    2015-07-09
42    2015-01-09
43    2015-08-09
44    2015-09-09
45    2015-09-13
46    2015-09-14
47    2015-09-24
48    2015-04-09
49    2015-09-14
50    2015-09-21
51    2015-09-28
52    2015-08-09
53    2015-09-15
54    2015-09-22
55    2015-09-29
56    2015-09-16
57    2015-09-23
58    2015-09-

In [1289]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format = '%d/%m/%Y')
#format helps to read Dates so you can use this column also!
# this is impportant to have this column when you have time related data as in this case!
#day month year hour minute second  ## this is the order

In [1290]:
type(df_reason_mod['Date']) #below you see I made it Series object

pandas.core.series.Series

In [1291]:
df_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   Reason_1                   700 non-null    uint8         
 1   Reason_2                   700 non-null    uint8         
 2   Reason_3                   700 non-null    uint8         
 3   Reason_4                   700 non-null    uint8         
 4   Date                       700 non-null    datetime64[ns]
 5   Transportation Expense     700 non-null    int64         
 6   Distance to Work           700 non-null    int64         
 7   Age                        700 non-null    int64         
 8   Daily Work Load Average    700 non-null    float64       
 9   Body Mass Index            700 non-null    int64         
 10  Education                  700 non-null    int64         
 11  Children                   700 non-null    int64         
 12  Pets    

## Extract the Month Value:

In [1292]:
df_reason_mod['Date'][0]

Timestamp('2015-07-07 00:00:00')

In [1293]:
df_reason_mod['Date'][0].month # you can use this method( already in python) to extract month info

7

In [1294]:
list_months = []
list_months

[]

In [1295]:
df_reason_mod.shape

(700, 14)

In [1296]:
for i in range(df_reason_mod.shape[0]):     #with the help of a loop I put everything in a list as month data
    list_months.append(df_reason_mod['Date'][i].month) 

In [1297]:
list_months

[7,
 7,
 7,
 7,
 7,
 10,
 7,
 7,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 5,
 12,
 3,
 10,
 8,
 8,
 8,
 4,
 12,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 4,
 8,
 8,
 8,
 1,
 7,
 1,
 8,
 9,
 9,
 9,
 9,
 4,
 9,
 9,
 9,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 11,
 9,
 9,
 6,
 10,
 10,
 10,
 10,
 10,
 6,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 5,
 4,
 5,
 12,
 11,
 2,
 9,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 2,
 10,
 11,
 11,
 1,
 1,
 2,
 2,
 3,
 4,
 8,
 9,
 10,
 11,
 12,
 12,
 11,
 12,
 12,
 6,
 4,
 5,
 5,
 6,
 7,
 7,
 8,
 11,
 12,
 12,
 1,
 1,
 1,
 11,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 5,
 3,
 10,
 11,
 11,
 12,
 12,
 8,
 9,
 2,
 9,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 8,
 3,
 3,
 2,
 3,
 4,
 4,
 7,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 6,
 4,
 12,
 4,
 4,
 4,
 4,
 6,
 7,
 8,
 8,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 8,
 4,
 4,
 5,
 2,
 3,
 3,
 11,
 9,
 10,
 4,
 11,
 5,
 5,
 5,
 5,
 11,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 3,
 7,
 8,
 9,
 10,
 6,
 6

In [1298]:
len(list_months)

700

In [1299]:
df_reason_mod['Month Value'] = list_months

In [1300]:
df_reason_mod.head(10) # here you can have month values in dataframe

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   
5         0         0         0         1 2015-10-07                     179   
6         0         0         0         1 2015-07-17                     361   
7         0         0         0         1 2015-07-24                     260   
8         0         0         1         0 2015-06-07                     155   
9         0         0         0         1 2015-07-13                     235   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   
5                51   38                  239.554               31          1   
6                52   28                  239.554               27          1   
7                50   36                  239.554               23          1   
8                12   34                  239.554               25          1   
9                11   37                  239.554               29          3   

   Children  Pets  Absenteeism Time in Hours  Month Value  
0         2     1                          4            7  
1         1     0                          0            7  
2         0     0                          2            7  
3         2     0                          4            7  
4         2     1                          2            7  
5         0     0                          2           10  
6         1     4                          8            7  
7         4     0                          4            7  
8         2     0                         40            6  
9         1     1                          8            7

## Extract the Day of the Week:

In [1301]:
df_reason_mod['Date'][500].weekday() # of course we will have numbers as days of the week
#weekday function will do that for us

2

In [1302]:
df_reason_mod['Date'][500]

Timestamp('2017-08-09 00:00:00')

In [1303]:
def date_to_weekday(date_value): # a way to modify date and extract days
    return date_value.weekday() # just return me weekdays from date values

In [1304]:
df_reason_mod['Day of the Week'] = df_reason_mod['Date'].apply(date_to_weekday)

In [1305]:
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

## Other columns:

In [1306]:
df_reason_mod = df_reason_mod.drop(['Date'], axis = 1)
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

In [1307]:
df_reason_mod.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month Value',
       'Day of the Week'], dtype=object)

In [1308]:
column_names_upd = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value', 'Day of the Week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours']

In [1309]:
df_reason_mod = df_reason_mod[column_names_upd]
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

In [1310]:
df_reason_date_mod = df_reason_mod.copy()
df_reason_date_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

In [1311]:
type(df_reason_date_mod['Transportation Expense'][0]) # we have int vallues for these columns
# just proceed

numpy.int64

In [1312]:
type(df_reason_date_mod['Distance to Work'][0])

numpy.int64

In [1313]:
type(df_reason_date_mod['Age'][0])

numpy.int64

In [1314]:
type(df_reason_date_mod['Daily Work Load Average'][0])

numpy.float64

In [1315]:
type(df_reason_date_mod['Body Mass Index'][0]) # children and pets are just fine


numpy.int64

## 'Education', 'Children', 'Pets'

In [1316]:
df_reason_date_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

In [1317]:
df_reason_date_mod['Education'].unique() # we have 4 education type  
#you can use mapping as each number can represent a rank respectively

array([1, 3, 2, 4])

In [1318]:
df_reason_date_mod['Education'].value_counts()
#for example 583 with high school degree
# 4 with post graduate  73 bachelors and 40 MSc

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [1319]:
df_reason_date_mod['Education'] = df_reason_date_mod['Education'].map({1:0, 2:1, 3:1, 4:1})
#just map evertyhing into 0 and 1
#highschool as 0, rest is 1

In [1320]:
df_reason_date_mod['Education'].unique()

array([0, 1])

In [1321]:
df_reason_date_mod['Education'].value_counts() #looks like we are done!

0    583
1    117
Name: Education, dtype: int64

## Children

In [1322]:
df_reason_date_mod['Children'].unique()

array([2, 1, 0, 4, 3])

In [1323]:
df_reason_date_mod['Children'].value_counts()

0    285
1    213
2    146
4     42
3     14
Name: Children, dtype: int64

In [1324]:
df_reason_date_mod['Children'] = df_reason_date_mod['Children'].map({0:0, 1:1, 2:2, 4:2, 3:2})

In [1325]:
df_reason_date_mod['Children'].unique()

array([2, 1, 0])

In [1326]:
df_reason_date_mod['Children'].value_counts()

0    285
1    213
2    202
Name: Children, dtype: int64

In [1327]:
df_reason_date_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Pets

In [1328]:
df_reason_date_mod['Pets'].unique()

array([1, 0, 4, 2, 5, 8])

In [1329]:
df_reason_date_mod['Pets'].value_counts()

0    439
1    132
2     92
4     29
5      5
8      3
Name: Pets, dtype: int64

In [1330]:
df_reason_date_mod['Pets'] = df_reason_date_mod['Pets'].map({0:0, 1:1, 2:1, 4:1, 5:1, 8:1})

In [1331]:
df_reason_date_mod['Pets'].unique()

array([1, 0])

In [1332]:
df_reason_date_mod['Pets'].value_counts()

0    439
1    261
Name: Pets, dtype: int64

In [1333]:
df_reason_date_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Daily Work Load Average

In [1334]:
df_reason_date_mod['Daily Work Load Average'].unique()

array([239.554, 205.917, 241.476, 253.465, 306.345, 261.306, 308.593,
       302.585, 343.253, 326.452, 378.884, 377.55 , 275.312, 265.615,
       294.217, 265.017, 284.031, 236.629, 330.061, 251.818, 244.387,
       239.409, 246.074, 253.957, 230.29 , 249.797, 261.756, 284.853,
       268.519, 280.549, 313.532, 264.249, 222.196, 246.288, 237.656])

In [1335]:
df_reason_date_mod['Daily Work Load Average'].value_counts()

222.196    36
264.249    33
343.253    29
265.017    28
237.656    26
284.853    25
308.593    24
268.519    23
244.387    22
241.476    22
284.031    22
205.917    21
251.818    21
246.288    20
326.452    20
230.290    20
253.957    19
239.554    19
236.629    19
294.217    19
253.465    18
265.615    18
302.585    18
306.345    18
246.074    16
275.312    16
377.550    16
378.884    16
249.797    15
280.549    15
313.532    15
261.306    15
239.409    13
261.756    12
330.061    11
Name: Daily Work Load Average, dtype: int64

## Age

In [1336]:
df_reason_date_mod['Age'].unique()

array([33, 50, 38, 39, 28, 36, 34, 37, 41, 47, 29, 48, 32, 27, 43, 40, 31,
       30, 49, 58, 46])

In [1337]:
df_reason_date_mod['Age'].value_counts()

38    113
28    113
37     70
40     55
36     49
33     48
30     41
50     35
41     34
34     27
47     24
43     23
31     17
32     13
29      7
27      7
39      7
58      6
48      5
49      5
46      1
Name: Age, dtype: int64

In [1338]:
df_reason_date_mod['Age'] = df_reason_date_mod['Age'].map({
    27:0,
    28:0,
    29:0,
    30:1,
    31:1,
    32:1,
    33:1,
    34:1,
    36:1,
    37:1,
    38:1,
    39:1,
    40:2,
    41:2,
    43:2,
    46:2,
    47:2,
    48:2,
    49:2,
    50:2,
    58:2,
})

In [1339]:
df_reason_date_mod['Age'].unique()

array([1, 2, 0])

In [1340]:
df_reason_date_mod['Age'].value_counts()

1    385
2    188
0    127
Name: Age, dtype: int64

## Body Mass Index

In [1341]:
df_reason_date_mod['Body Mass Index'].unique()

array([30, 31, 24, 27, 23, 25, 29, 32, 22, 33, 21, 28, 38, 19, 36, 35])

In [1342]:
df_reason_date_mod['Body Mass Index'].min()

19

In [1343]:
df_reason_date_mod['Body Mass Index'].max()

38

In [1344]:
df_reason_date_mod['Body Mass Index'].value_counts().groupby(level=0).mean()

19     41.0
21     17.0
22     32.0
23     75.0
24     84.0
25    118.0
27     22.0
28     52.0
29     22.0
30     39.0
31    145.0
32     24.0
33      5.0
35      1.0
36      5.0
38     18.0
Name: Body Mass Index, dtype: float64

In [1345]:
df_reason_date_mod['Body Mass Index'] = df_reason_date_mod['Body Mass Index'].map({
    19:0,
    21:0,
    22:0,
    23:0,
    24:0,
    25:1,
    27:1,
    28:1,
    29:1,
    30:2,
    31:2,
    32:2,
    33:2,
    35:2,
    36:2,
    38:2,
})

In [1346]:
df_reason_date_mod['Body Mass Index'].unique()

array([2, 0, 1])

In [1347]:
df_reason_date_mod['Body Mass Index'].value_counts()

0    249
2    237
1    214
Name: Body Mass Index, dtype: int64

## Daily Work Load Average

In [1348]:
df_reason_date_mod = df_reason_date_mod.drop(['Daily Work Load Average'], axis = 1)

## Absenteeism Time in Hours

In [1349]:
df_reason_date_mod['Absenteeism Time in Hours'].unique()

array([  4,   0,   2,   8,  40,   1,   7,   3,  32,   5,  16,  24,  64,
        56,  80, 120, 112, 104,  48])

In [1350]:
df_reason_date_mod['Absenteeism Time in Hours'].value_counts()

8      195
2      149
3      106
1       87
4       57
0       39
16      18
24      15
5        7
40       7
32       6
64       3
56       2
80       2
120      2
112      2
7        1
104      1
48       1
Name: Absenteeism Time in Hours, dtype: int64

In [1351]:
df_reason_date_mod['Absenteeism Time in Hours'].min()

0

In [1352]:
df_reason_date_mod['Absenteeism Time in Hours'].max()

120

In [1353]:
df_reason_date_mod['Absenteeism Time in Hours'].value_counts().groupby(level=0).mean()

0       39.0
1       87.0
2      149.0
3      106.0
4       57.0
5        7.0
7        1.0
8      195.0
16      18.0
24      15.0
32       6.0
40       7.0
48       1.0
56       2.0
64       3.0
80       2.0
104      1.0
112      2.0
120      2.0
Name: Absenteeism Time in Hours, dtype: float64

In [1354]:
df_reason_date_mod['Absenteeism Time in Hours'] = df_reason_date_mod['Absenteeism Time in Hours'].map({
    0:0,
    1:0,
    2:0,
    3:1,
    4:1,
    5:1,
    7:2,
    8:2,
    16:2,
    24:2,
    32:2,
    40:2,
    48:2,
    56:2,
    64:2,
    80:2,
    104:2,
    112:2,
    120:2,
})

In [1355]:
df_reason_date_mod['Absenteeism Time in Hours'].unique()

array([1, 0, 2])

In [1356]:
df_reason_date_mod['Absenteeism Time in Hours'].value_counts()

0    275
2    255
1    170
Name: Absenteeism Time in Hours, dtype: int64

## Distance to Work

In [1357]:
df_reason_date_mod['Distance to Work'].unique()

array([36, 13, 51,  5, 52, 50, 12, 11, 25, 29, 16, 27, 42, 10, 20, 31, 26,
       17, 22, 15, 49, 48, 14, 35])

In [1358]:
df_reason_date_mod['Distance to Work'].value_counts()

26    121
51    116
25     54
10     48
50     45
36     39
31     36
13     32
12     27
16     26
11     24
52     22
22     19
20     18
17     14
29     12
15      8
49      7
42      7
27      7
5       6
14      6
48      5
35      1
Name: Distance to Work, dtype: int64

In [1359]:
df_reason_date_mod['Distance to Work'].value_counts().groupby(level=0).mean()

5       6.0
10     48.0
11     24.0
12     27.0
13     32.0
14      6.0
15      8.0
16     26.0
17     14.0
20     18.0
22     19.0
25     54.0
26    121.0
27      7.0
29     12.0
31     36.0
35      1.0
36     39.0
42      7.0
48      5.0
49      7.0
50     45.0
51    116.0
52     22.0
Name: Distance to Work, dtype: float64

In [1360]:
df_reason_date_mod['Distance to Work'] = df_reason_date_mod['Distance to Work'].map({
    5:0,
    10:0,
    11:0,
    12:0,
    13:0,
    14:0,
    15:0,
    16:0,
    17:0,
    20:0,
    22:1,
    25:1,
    26:1,
    27:1,
    29:1,
    31:2,
    35:2,
    36:2,
    42:2,
    48:2,
    49:2,
    50:2,
    51:2,
    52:2,
})

In [1361]:
df_reason_date_mod['Distance to Work'].unique()

array([2, 0, 1])

In [1362]:
df_reason_date_mod['Distance to Work'].value_counts()

2    278
1    213
0    209
Name: Distance to Work, dtype: int64

## Transportation Expense

In [1363]:
df_reason_date_mod['Transportation Expense'].unique()

array([289, 118, 179, 279, 361, 260, 155, 235, 246, 189, 248, 330, 157,
       291, 184, 225, 369, 388, 378, 228, 300, 268, 231, 233])

In [1364]:
df_reason_date_mod['Transportation Expense'].value_counts()

179    173
118     81
225     79
235     55
289     44
260     42
291     39
246     30
155     27
248     24
361     22
330     16
369     14
378      7
157      7
184      7
189      7
279      6
228      6
300      5
388      3
233      3
268      2
231      1
Name: Transportation Expense, dtype: int64

In [1365]:
df_reason_date_mod['Transportation Expense'].value_counts()

179    173
118     81
225     79
235     55
289     44
260     42
291     39
246     30
155     27
248     24
361     22
330     16
369     14
378      7
157      7
184      7
189      7
279      6
228      6
300      5
388      3
233      3
268      2
231      1
Name: Transportation Expense, dtype: int64

In [1366]:
df_reason_date_mod['Transportation Expense'].value_counts().groupby(level=0).mean()

118     81.0
155     27.0
157      7.0
179    173.0
184      7.0
189      7.0
225     79.0
228      6.0
231      1.0
233      3.0
235     55.0
246     30.0
248     24.0
260     42.0
268      2.0
279      6.0
289     44.0
291     39.0
300      5.0
330     16.0
361     22.0
369     14.0
378      7.0
388      3.0
Name: Transportation Expense, dtype: float64

In [1367]:
df_reason_date_mod['Transportation Expense'] = df_reason_date_mod['Transportation Expense'].map({
    118:0,
    155:0,
    157:0,
    179:0,
    184:0,
    189:0,
    225:1,
    228:1,
    231:1,
    233:1,
    235:1,
    246:1,
    248:1,
    260:1,
    268:1,
    279:1,
    289:1,
    291:1,
    300:1,
    330:2,
    361:2,
    369:2,
    378:2,
    388:2,
})

In [1368]:
df_reason_date_mod['Transportation Expense'].unique()

array([1, 0, 2])

In [1369]:
df_reason_date_mod['Transportation Expense'].value_counts()

1    336
0    302
2     62
Name: Transportation Expense, dtype: int64

## Final Checkpoint

In [1370]:
#now you made it, you know how to manipulate complex data
#you can use this data for machine learning tasks
# can you predict absenteeism or maybe age or any other

df_cleaned = df_reason_date_mod.copy()
df_cleaned.head(10) 

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   
5         0         0         0         1           10                2   
6         0         0         0         1            7                4   
7         0         0         0         1            7                4   
8         0         0         1         0            6                6   
9         0         0         0         1            7                0   

   Transportation Expense  Distance to Work  Age  Body Mass Index  Education  \
0                       1                 2    1                2          0   
1                       0                 0    2                2          0   
2                       0                 2    1                2          0   
3                       1                 0    1                0          0   
4                       1                 2    1                2          0   
5                       0                 2    1                2          0   
6                       2                 2    0                1          0   
7                       1                 2    1                0          0   
8                       0                 0    1                1          0   
9                       1                 0    1                1          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          1  
1         1     0                          0  
2         0     0                          0  
3         2     0                          1  
4         2     1                          0  
5         0     0                          0  
6         1     1                          2  
7         2     0                          1  
8         2     0                          2  
9         1     1                          2

In [1371]:
# Exporting the data to a CSV (Comma Separated Values) file
df_cleaned.to_csv("AbsenteeismCleaned_Yury.csv")